plantevi_rich <- list()
plantevi_rich[[1]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + (1|pb_rich_evi$month))
plantevi_rich[[2]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$plant_rich*pb_rich_evi$evi + (1|pb_rich_evi$month))
plantevi_rich[[3]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + (1|pb_rich_evi$month))
plantevi_rich[[4]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$scelev + (1|pb_rich_evi$month))
plantevi_rich[[5]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$evi*pb_rich_evi$scelev + (1|pb_rich_evi$month))
plantevi_rich[[6]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + (1|pb_rich_evi$month))
plantevi_rich[[7]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + pb_rich_evi$plant_rich*pb_rich_evi$scelev + (1|pb_rich_evi$month))
plantevi_rich[[8]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + pb_rich_evi$evi*pb_rich_evi$scelev + (1|pb_rich_evi$month))
plantevi_rich[[9]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + pb_rich_evi$plant_rich*pb_rich_evi$scelev + pb_rich_evi$evi*pb_rich_evi$scelev + (1|pb_rich_evi$month))

spring_rich<-pb_rich_evi %>%
  filter(month >= 2 & month <= 5)
plantevi_rich[[10]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + (1|spring_rich$month))
plantevi_rich[[11]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$plant_rich*spring_rich$evi + (1|spring_rich$month))
plantevi_rich[[12]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + (1|spring_rich$month))
plantevi_rich[[13]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$scelev + (1|spring_rich$month))
plantevi_rich[[14]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$evi*spring_rich$scelev + (1|spring_rich$month))
plantevi_rich[[15]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + (1|spring_rich$month))
plantevi_rich[[16]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + spring_rich$plant_rich*spring_rich$scelev + (1|spring_rich$month))
plantevi_rich[[17]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + spring_rich$evi*spring_rich$scelev + (1|spring_rich$month))
plantevi_rich[[18]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + spring_rich$plant_rich*spring_rich$scelev + spring_rich$evi*spring_rich$scelev + (1|spring_rich$month))

fall_rich<-pb_rich_evi %>%
  filter(month >= 5 & month <= 11)
plantevi_rich[[19]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + (1|fall_rich$month))
plantevi_rich[[20]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$plant_rich*fall_rich$evi + (1|fall_rich$month))
plantevi_rich[[21]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + (1|fall_rich$month))
plantevi_rich[[22]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$scelev + (1|fall_rich$month))
plantevi_rich[[23]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$evi*fall_rich$scelev + (1|fall_rich$month))
plantevi_rich[[24]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + (1|fall_rich$month))
plantevi_rich[[25]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + fall_rich$plant_rich*fall_rich$scelev + (1|fall_rich$month))
plantevi_rich[[26]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + fall_rich$evi*fall_rich$scelev + (1|fall_rich$month))
plantevi_rich[[27]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + fall_rich$plant_rich*fall_rich$scelev + fall_rich$evi*fall_rich$scelev + (1|fall_rich$month))

alex_data<-pb_sp_evi %>%
  filter(spname == 'Archilochusalexandri')
plantevi_alex <- list()
plantevi_alex[[1]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + (1|alex_data$month))
plantevi_alex[[2]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$plant_rich*alex_data$evi + (1|alex_data$month))
plantevi_alex[[3]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + (1|alex_data$month))
plantevi_alex[[4]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$scelev + (1|alex_data$month))
plantevi_alex[[5]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$evi*alex_data$scelev + (1|alex_data$month))
plantevi_alex[[6]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + (1|alex_data$month))
plantevi_alex[[7]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + alex_data$plant_rich*alex_data$scelev + (1|alex_data$month))
plantevi_alex[[8]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + alex_data$evi*alex_data$scelev + (1|alex_data$month))
plantevi_alex[[9]] <- glmer(cbind(alex_data$rich,4-alex_data$rich) ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + alex_data$plant_rich*alex_data$scelev + alex_data$evi*alex_data$scelev + (1|alex_data$month))

alex_spring<-alex_data %>% filter(month >= 2 & month <= 6)
plantevi_alex[[10]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + (1|alex_spring$month))
plantevi_alex[[11]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$plant_rich*alex_spring$evi + (1|alex_spring$month))
plantevi_alex[[12]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + (1|alex_spring$month))
plantevi_alex[[13]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$scelev + (1|alex_spring$month))
plantevi_alex[[14]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$evi*alex_spring$scelev + (1|alex_spring$month))
plantevi_alex[[15]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + (1|alex_spring$month))
plantevi_alex[[16]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + alex_spring$plant_rich*alex_spring$scelev + (1|alex_spring$month))
plantevi_alex[[17]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + alex_spring$evi*alex_spring$scelev + (1|alex_spring$month))
plantevi_alex[[18]] <- glmer(cbind(alex_spring$rich,4-alex_spring$rich) ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + alex_spring$plant_rich*alex_spring$scelev + alex_spring$evi*alex_spring$scelev + (1|alex_spring$month))

alex_fall<-alex_data %>% filter(month >= 6 & month <= 12)
plantevi_alex[[19]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + (1|alex_fall$month))
plantevi_alex[[20]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$plant_rich*alex_fall$evi + (1|alex_fall$month))
plantevi_alex[[21]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + (1|alex_fall$month))
plantevi_alex[[22]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$scelev + (1|alex_fall$month))
plantevi_alex[[23]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$evi*alex_fall$scelev + (1|alex_fall$month))
plantevi_alex[[24]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + (1|alex_fall$month))
plantevi_alex[[25]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + alex_fall$plant_rich*alex_fall$scelev + (1|alex_fall$month))
plantevi_alex[[26]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + alex_fall$evi*alex_fall$scelev + (1|alex_fall$month))
plantevi_alex[[27]] <- glmer(cbind(alex_fall$rich,4-alex_fall$rich) ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + alex_fall$plant_rich*alex_fall$scelev + alex_fall$evi*alex_fall$scelev + (1|alex_fall$month))
