plantevi_rich <- list()
plantevi_rich[[1]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[2]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$plant_rich*pb_rich_evi$evi + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[3]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[4]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$scelev + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[5]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$evi*pb_rich_evi$scelev + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[6]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[7]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + pb_rich_evi$plant_rich*pb_rich_evi$scelev + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[8]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + pb_rich_evi$evi*pb_rich_evi$scelev + (1|pb_rich_evi$month), family = binomial)
plantevi_rich[[9]] <- glmer(cbind(pb_rich_evi$rich,4-pb_rich_evi$rich) ~ pb_rich_evi$plant_rich + pb_rich_evi$evi + pb_rich_evi$scelev + pb_rich_evi$plant_rich*pb_rich_evi$evi + pb_rich_evi$plant_rich*pb_rich_evi$scelev + pb_rich_evi$evi*pb_rich_evi$scelev + (1|pb_rich_evi$month), family = binomial)

spring_rich<-pb_rich_evi %>%
  filter(month >= 2 & month <= 5)
plantevi_rich[[10]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + (1|spring_rich$month), family = binomial)
plantevi_rich[[11]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$plant_rich*spring_rich$evi + (1|spring_rich$month), family = binomial)
plantevi_rich[[12]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + (1|spring_rich$month), family = binomial)
plantevi_rich[[13]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$scelev + (1|spring_rich$month), family = binomial)
plantevi_rich[[14]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$evi*spring_rich$scelev + (1|spring_rich$month), family = binomial)
plantevi_rich[[15]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + (1|spring_rich$month), family = binomial)
plantevi_rich[[16]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + spring_rich$plant_rich*spring_rich$scelev + (1|spring_rich$month), family = binomial)
plantevi_rich[[17]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + spring_rich$evi*spring_rich$scelev + (1|spring_rich$month), family = binomial)
plantevi_rich[[18]] <- glmer(cbind(spring_rich$rich,4-spring_rich$rich) ~ spring_rich$plant_rich + spring_rich$evi + spring_rich$scelev + spring_rich$plant_rich*spring_rich$evi + spring_rich$plant_rich*spring_rich$scelev + spring_rich$evi*spring_rich$scelev + (1|spring_rich$month), family = binomial)

fall_rich<-pb_rich_evi %>%
  filter(month >= 5 & month <= 11)
plantevi_rich[[19]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + (1|fall_rich$month), family = binomial)
plantevi_rich[[20]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$plant_rich*fall_rich$evi + (1|fall_rich$month), family = binomial)
plantevi_rich[[21]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + (1|fall_rich$month), family = binomial)
plantevi_rich[[22]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$scelev + (1|fall_rich$month), family = binomial)
plantevi_rich[[23]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$evi*fall_rich$scelev + (1|fall_rich$month), family = binomial)
plantevi_rich[[24]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + (1|fall_rich$month), family = binomial)
plantevi_rich[[25]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + fall_rich$plant_rich*fall_rich$scelev + (1|fall_rich$month), family = binomial)
plantevi_rich[[26]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + fall_rich$evi*fall_rich$scelev + (1|fall_rich$month), family = binomial)
plantevi_rich[[27]] <- glmer(cbind(fall_rich$rich,4-fall_rich$rich) ~ fall_rich$plant_rich + fall_rich$evi + fall_rich$scelev + fall_rich$plant_rich*fall_rich$evi + fall_rich$plant_rich*fall_rich$scelev + fall_rich$evi*fall_rich$scelev + (1|fall_rich$month), family = binomial)

alex_data<-pb_sp_evi %>%
  filter(spname == 'Archilochusalexandri')
plantevi_alex <- list()
plantevi_alex[[1]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + (1|alex_data$month), family = binomial)
plantevi_alex[[2]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$plant_rich*alex_data$evi + (1|alex_data$month), family = binomial)
plantevi_alex[[3]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + (1|alex_data$month), family = binomial)
plantevi_alex[[4]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$scelev + (1|alex_data$month), family = binomial)
plantevi_alex[[5]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$evi*alex_data$scelev + (1|alex_data$month), family = binomial)
plantevi_alex[[6]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + (1|alex_data$month), family = binomial)
plantevi_alex[[7]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + alex_data$plant_rich*alex_data$scelev + (1|alex_data$month), family = binomial)
plantevi_alex[[8]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + alex_data$evi*alex_data$scelev + (1|alex_data$month), family = binomial)
plantevi_alex[[9]] <- glmer(alex_data$presence ~ alex_data$plant_rich + alex_data$evi + alex_data$scelev + alex_data$plant_rich*alex_data$evi + alex_data$plant_rich*alex_data$scelev + alex_data$evi*alex_data$scelev + (1|alex_data$month), family = binomial)

alex_spring<-alex_data %>% filter(month >= 2 & month <= 6)
plantevi_alex[[10]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + (1|alex_spring$month), family = binomial)
plantevi_alex[[11]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$plant_rich*alex_spring$evi + (1|alex_spring$month), family = binomial)
plantevi_alex[[12]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + (1|alex_spring$month), family = binomial)
plantevi_alex[[13]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$scelev + (1|alex_spring$month), family = binomial)
plantevi_alex[[14]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$evi*alex_spring$scelev + (1|alex_spring$month), family = binomial)
plantevi_alex[[15]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + (1|alex_spring$month), family = binomial)
plantevi_alex[[16]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + alex_spring$plant_rich*alex_spring$scelev + (1|alex_spring$month), family = binomial)
plantevi_alex[[17]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + alex_spring$evi*alex_spring$scelev + (1|alex_spring$month), family = binomial)
plantevi_alex[[18]] <- glmer(alex_spring$presence ~ alex_spring$plant_rich + alex_spring$evi + alex_spring$scelev + alex_spring$plant_rich*alex_spring$evi + alex_spring$plant_rich*alex_spring$scelev + alex_spring$evi*alex_spring$scelev + (1|alex_spring$month), family = binomial)

alex_fall<-alex_data %>% filter(month >= 6 & month <= 12)
plantevi_alex[[19]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + (1|alex_fall$month), family = binomial)
plantevi_alex[[20]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$plant_rich*alex_fall$evi + (1|alex_fall$month), family = binomial)
plantevi_alex[[21]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + (1|alex_fall$month), family = binomial)
plantevi_alex[[22]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$scelev + (1|alex_fall$month), family = binomial)
plantevi_alex[[23]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$evi*alex_fall$scelev + (1|alex_fall$month), family = binomial)
plantevi_alex[[24]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + (1|alex_fall$month), family = binomial)
plantevi_alex[[25]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + alex_fall$plant_rich*alex_fall$scelev + (1|alex_fall$month), family = binomial)
plantevi_alex[[26]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + alex_fall$evi*alex_fall$scelev + (1|alex_fall$month), family = binomial)
plantevi_alex[[27]] <- glmer(alex_fall$presence ~ alex_fall$plant_rich + alex_fall$evi + alex_fall$scelev + alex_fall$plant_rich*alex_fall$evi + alex_fall$plant_rich*alex_fall$scelev + alex_fall$evi*alex_fall$scelev + (1|alex_fall$month), family = binomial)

cal_data<-pb_sp_evi %>% filter(spname == 'Selasphoruscalliope')
plantevi_cal <- list()
plantevi_cal[[1]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + (1|cal_data$month), family = binomial)
plantevi_cal[[2]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$plant_rich*cal_data$evi + (1|cal_data$month), family = binomial)
plantevi_cal[[3]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + (1|cal_data$month), family = binomial)
plantevi_cal[[4]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + cal_data$plant_rich*cal_data$scelev + (1|cal_data$month), family = binomial)
plantevi_cal[[5]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + cal_data$evi*cal_data$scelev + (1|cal_data$month), family = binomial)
plantevi_cal[[6]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + cal_data$plant_rich*cal_data$evi + (1|cal_data$month), family = binomial)
plantevi_cal[[7]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + cal_data$plant_rich*cal_data$evi + cal_data$plant_rich*cal_data$scelev + (1|cal_data$month), family = binomial)
plantevi_cal[[8]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + cal_data$plant_rich*cal_data$evi + cal_data$evi*cal_data$scelev + (1|cal_data$month), family = binomial)
plantevi_cal[[9]] <- glmer(cal_data$presence ~ cal_data$plant_rich + cal_data$evi + cal_data$scelev + cal_data$plant_rich*cal_data$evi + cal_data$plant_rich*cal_data$scelev + cal_data$evi*cal_data$scelev + (1|cal_data$month), family = binomial)

cal_spring<-cal_data %>% filter(month >= 3 & month <= 5)
plantevi_cal[[10]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + (1|cal_spring$month), family = binomial)
plantevi_cal[[11]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$plant_rich*cal_spring$evi + (1|cal_spring$month), family = binomial)
plantevi_cal[[12]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + (1|cal_spring$month), family = binomial)
plantevi_cal[[13]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + cal_spring$plant_rich*cal_spring$scelev + (1|cal_spring$month), family = binomial)
plantevi_cal[[14]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + cal_spring$evi*cal_spring$scelev + (1|cal_spring$month), family = binomial)
plantevi_cal[[15]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + cal_spring$plant_rich*cal_spring$evi + (1|cal_spring$month), family = binomial)
plantevi_cal[[16]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + cal_spring$plant_rich*cal_spring$evi + cal_spring$plant_rich*cal_spring$scelev + (1|cal_spring$month), family = binomial)
plantevi_cal[[17]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + cal_spring$plant_rich*cal_spring$evi + cal_spring$evi*cal_spring$scelev + (1|cal_spring$month), family = binomial)
plantevi_cal[[18]] <- glmer(cal_spring$presence ~ cal_spring$plant_rich + cal_spring$evi + cal_spring$scelev + cal_spring$plant_rich*cal_spring$evi + cal_spring$plant_rich*cal_spring$scelev + cal_spring$evi*cal_spring$scelev + (1|cal_spring$month), family = binomial)

cal_fall<-cal_data %>% filter(month >= 5 & month <= 11)
plantevi_cal[[19]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + (1|cal_fall$month), family = binomial)
plantevi_cal[[20]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$plant_rich*cal_fall$evi + (1|cal_fall$month), family = binomial)
plantevi_cal[[21]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + (1|cal_fall$month), family = binomial)
plantevi_cal[[22]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + cal_fall$plant_rich*cal_fall$scelev + (1|cal_fall$month), family = binomial)
plantevi_cal[[23]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + cal_fall$evi*cal_fall$scelev + (1|cal_fall$month), family = binomial)
plantevi_cal[[24]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + cal_fall$plant_rich*cal_fall$evi + (1|cal_fall$month), family = binomial)
plantevi_cal[[25]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + cal_fall$plant_rich*cal_fall$evi + cal_fall$plant_rich*cal_fall$scelev + (1|cal_fall$month), family = binomial)
plantevi_cal[[26]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + cal_fall$plant_rich*cal_fall$evi + cal_fall$evi*cal_fall$scelev + (1|cal_fall$month), family = binomial)
plantevi_cal[[27]] <- glmer(cal_fall$presence ~ cal_fall$plant_rich + cal_fall$evi + cal_fall$scelev + cal_fall$plant_rich*cal_fall$evi + cal_fall$plant_rich*cal_fall$scelev + cal_fall$evi*cal_fall$scelev + (1|cal_fall$month), family = binomial)

plat_data<-pb_sp_evi %>% filter(spname == 'Selasphorusplatycercus')
plantevi_plat <- list()
plantevi_plat[[1]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + (1|plat_data$month), family = binomial)
plantevi_plat[[2]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$plant_rich*plat_data$evi + (1|plat_data$month), family = binomial)
plantevi_plat[[3]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + (1|plat_data$month), family = binomial)
plantevi_plat[[4]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + plat_data$plant_rich*plat_data$scelev + (1|plat_data$month), family = binomial)
plantevi_plat[[5]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + plat_data$evi*plat_data$scelev + (1|plat_data$month), family = binomial)
plantevi_plat[[6]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + plat_data$plant_rich*plat_data$evi + (1|plat_data$month), family = binomial)
plantevi_plat[[7]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + plat_data$plant_rich*plat_data$evi + plat_data$plant_rich*plat_data$scelev + (1|plat_data$month), family = binomial)
plantevi_plat[[8]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + plat_data$plant_rich*plat_data$evi + plat_data$evi*plat_data$scelev + (1|plat_data$month), family = binomial)
plantevi_plat[[9]] <- glmer(plat_data$presence ~ plat_data$plant_rich + plat_data$evi + plat_data$scelev + plat_data$plant_rich*plat_data$evi + plat_data$plant_rich*plat_data$scelev + plat_data$evi*plat_data$scelev + (1|plat_data$month), family = binomial)

plat_spring<-plat_data %>% filter(month >= 2 & month <= 7)
plantevi_plat[[10]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + (1|plat_spring$month), family = binomial)
plantevi_plat[[11]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$plant_rich*plat_spring$evi + (1|plat_spring$month), family = binomial)
plantevi_plat[[12]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + (1|plat_spring$month), family = binomial)
plantevi_plat[[13]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + plat_spring$plant_rich*plat_spring$scelev + (1|plat_spring$month), family = binomial)
plantevi_plat[[14]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + plat_spring$evi*plat_spring$scelev + (1|plat_spring$month), family = binomial)
plantevi_plat[[15]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + plat_spring$plant_rich*plat_spring$evi + (1|plat_spring$month), family = binomial)
plantevi_plat[[16]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + plat_spring$plant_rich*plat_spring$evi + plat_spring$plant_rich*plat_spring$scelev + (1|plat_spring$month), family = binomial)
plantevi_plat[[17]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + plat_spring$plant_rich*plat_spring$evi + plat_spring$evi*plat_spring$scelev + (1|plat_spring$month), family = binomial)
plantevi_plat[[18]] <- glmer(plat_spring$presence ~ plat_spring$plant_rich + plat_spring$evi + plat_spring$scelev + plat_spring$plant_rich*plat_spring$evi + plat_spring$plant_rich*plat_spring$scelev + plat_spring$evi*plat_spring$scelev + (1|plat_spring$month), family = binomial)

plat_fall<-plat_data %>% filter(month >= 7 & month <= 12)
plantevi_plat[[19]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + (1|plat_fall$month), family = binomial)
plantevi_plat[[20]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$plant_rich*plat_fall$evi + (1|plat_fall$month), family = binomial)
plantevi_plat[[21]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + (1|plat_fall$month), family = binomial)
plantevi_plat[[22]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + plat_fall$plant_rich*plat_fall$scelev + (1|plat_fall$month), family = binomial)
plantevi_plat[[23]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + plat_fall$evi*plat_fall$scelev + (1|plat_fall$month), family = binomial)
plantevi_plat[[24]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + plat_fall$plant_rich*plat_fall$evi + (1|plat_fall$month), family = binomial)
plantevi_plat[[25]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + plat_fall$plant_rich*plat_fall$evi + plat_fall$plant_rich*plat_fall$scelev + (1|plat_fall$month), family = binomial)
plantevi_plat[[26]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + plat_fall$plant_rich*plat_fall$evi + plat_fall$evi*plat_fall$scelev + (1|plat_fall$month), family = binomial)
plantevi_plat[[27]] <- glmer(plat_fall$presence ~ plat_fall$plant_rich + plat_fall$evi + plat_fall$scelev + plat_fall$plant_rich*plat_fall$evi + plat_fall$plant_rich*plat_fall$scelev + plat_fall$evi*plat_fall$scelev + (1|plat_fall$month), family = binomial)

ruf_data<-pb_sp_evi %>% filter(spname == 'Selasphorusrufus')
plantevi_ruf <- list()
plantevi_ruf[[1]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + (1|ruf_data$month), family = binomial)
plantevi_ruf[[2]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$plant_rich*ruf_data$evi + (1|ruf_data$month), family = binomial)
plantevi_ruf[[3]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + (1|ruf_data$month), family = binomial)
plantevi_ruf[[4]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + ruf_data$plant_rich*ruf_data$scelev + (1|ruf_data$month), family = binomial)
plantevi_ruf[[5]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + ruf_data$evi*ruf_data$scelev + (1|ruf_data$month), family = binomial)
plantevi_ruf[[6]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + ruf_data$plant_rich*ruf_data$evi + (1|ruf_data$month), family = binomial)
plantevi_ruf[[7]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + ruf_data$plant_rich*ruf_data$evi + ruf_data$plant_rich*ruf_data$scelev + (1|ruf_data$month), family = binomial)
plantevi_ruf[[8]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + ruf_data$plant_rich*ruf_data$evi + ruf_data$evi*ruf_data$scelev + (1|ruf_data$month), family = binomial)
plantevi_ruf[[9]] <- glmer(ruf_data$presence ~ ruf_data$plant_rich + ruf_data$evi + ruf_data$scelev + ruf_data$plant_rich*ruf_data$evi + ruf_data$plant_rich*ruf_data$scelev + ruf_data$evi*ruf_data$scelev + (1|ruf_data$month), family = binomial)

ruf_spring<-ruf_data %>% filter(month >= 1 & month <= 5)
plantevi_ruf[[10]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[11]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$plant_rich*ruf_spring$evi + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[12]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[13]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + ruf_spring$plant_rich*ruf_spring$scelev + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[14]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + ruf_spring$evi*ruf_spring$scelev + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[15]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + ruf_spring$plant_rich*ruf_spring$evi + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[16]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + ruf_spring$plant_rich*ruf_spring$evi + ruf_spring$plant_rich*ruf_spring$scelev + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[17]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + ruf_spring$plant_rich*ruf_spring$evi + ruf_spring$evi*ruf_spring$scelev + (1|ruf_spring$month), family = binomial)
plantevi_ruf[[18]] <- glmer(ruf_spring$presence ~ ruf_spring$plant_rich + ruf_spring$evi + ruf_spring$scelev + ruf_spring$plant_rich*ruf_spring$evi + ruf_spring$plant_rich*ruf_spring$scelev + ruf_spring$evi*ruf_spring$scelev + (1|ruf_spring$month), family = binomial)

ruf_fall<-ruf_data %>% filter(month >= 5 & month <= 11)
plantevi_ruf[[19]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[20]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$plant_rich*ruf_fall$evi + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[21]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[22]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + ruf_fall$plant_rich*ruf_fall$scelev + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[23]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + ruf_fall$evi*ruf_fall$scelev + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[24]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + ruf_fall$plant_rich*ruf_fall$evi + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[25]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + ruf_fall$plant_rich*ruf_fall$evi + ruf_fall$plant_rich*ruf_fall$scelev + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[26]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + ruf_fall$plant_rich*ruf_fall$evi + ruf_fall$evi*ruf_fall$scelev + (1|ruf_fall$month), family = binomial)
plantevi_ruf[[27]] <- glmer(ruf_fall$presence ~ ruf_fall$plant_rich + ruf_fall$evi + ruf_fall$scelev + ruf_fall$plant_rich*ruf_fall$evi + ruf_fall$plant_rich*ruf_fall$scelev + ruf_fall$evi*ruf_fall$scelev + (1|ruf_fall$month), family = binomial)

plantevi_rich_rsq <- lapply(plantevi_rich, function(x) r.squaredGLMM(x))
plantevi_alex_rsq <- lapply(plantevi_alex, function(x) r.squaredGLMM(x))
plantevi_cal_rsq <- lapply(plantevi_cal, function(x) r.squaredGLMM(x))
plantevi_plat_rsq <- lapply(plantevi_plat, function(x) r.squaredGLMM(x))
plantevi_ruf_rsq <- lapply(plantevi_ruf, function(x) r.squaredGLMM(x))
